//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : army_tool_function
//  @ File Name : ToolFunctionSet.h
//  @ Date : 2012/12/27
//  @ Author : @sunyb
//
//


#if !defined(_TOOLFUNCTIONSET_H)
#define _TOOLFUNCTIONSET_H

class ToolFunctionSet
{
public:
	ToolFunctionSet();
   ~ToolFunctionSet();
public:
	/* 输出调试信息 */
    void PrintfDebug(TCHAR * pszFormat, ...);
	/* 获得系统当前运行路径 */
    void GetCurExePath(TCHAR * pExePath);
	/* 多字节转宽字符 */
    bool MByteToWChar(LPCSTR lpcszStr, DWORD dwBufSize, LPWSTR lpwszStr);
	/* 宽字符转多字节 */
    bool WCharToMByte(LPWSTR lpwszStr, DWORD dwBufSize, LPSTR lpcszStr);
	/* 获得当前系统时间 */
	bool GetSysCurrentTime(TCHAR* pszSystime, DWORD dwSize);
	/* 转换字符串为多字节 */
	bool ConvertToMChar(CHAR *pszDes, int iDesSize, TCHAR *pszSrc);
	/* 转换字符串为宽字符*/
	bool ConvertToWChar(WCHAR *pszDes, int iDesSize, TCHAR *pszSrc);
};

#endif  //_TOOLFUNCTIONSET_H
